http {

    #Aun no implementado
    client_max_body_size aaaa;  #NO Valido, Valor por defecto: Maximo 1Mega
    client_max_body_size ;      #NO Valido, Valor por defecto: Maximo 1Mega
    client_max_body_size 56HF;  #NO Valido, Valor por defecto: Maximo 1Mega
    client_max_body_size 999G;  #NO Valido, Valor por defecto: Maximo 10Gigas
    client_max_body_size 0;     #NO Valido, Valor por defecto: Maximo 1Mega

    client_max_body_size 10M;   #Valido Maximo 10Megas
    client_max_body_size 10m;   #Valido Maximo 10Megas
    client_max_body_size 10G;   #Valido Maximo 10Megas
    client_max_body_size 10g;   #Valido Maximo 10Megas
    client_max_body_size 10K;   #Valido Maximo 10bytes
    client_max_body_size 10k;   #Valido Maximo 10bytes
    client_max_body_size 20;    #Valido Maximo 20bytes


    server
    {
        
        listen;         #funciona 8080 puerto predefinido
        listen aaa;     #Error no se puede cargar No es un numero
        listen 0 ;      #Error no se puede cargar
        listen 440;     #Error al vincular puerto 3 - menos de 1024 son puertos privilegiados (requieren sudo ./webserv conf/server.conf)
        listen 8080;    #funciona Entre 1024-49151: Puertos registrados (No requieren sudo)
        listen 65536;   #Error no se puede cargar - no existen el puertos superiores al 65536 y en adelante (TCP es de 16 bits 2^16 = 65,536)

        root html;      #funciona
        root asdasd;    #Error 404
        root;           #Error 404
        sinroot;        #Error 404
        
        index index.html;   #funciona
        index asdas.html;   #Error 404
        index;              #Error 404
        sin index;          #Error 404

        error_page 400 /templates/error400.html;
        error_page 403 /templates/error403.html;
        error_page 404 /templates/error404.html;
        error_page 405 /templates/error405.html;
        error_page 413 /templates/error413.html;
        error_page 418 /templates/error418.html;
        error_page 500 /templates/error500.html;
        error_page 501 /templates/error501.html;
        
        location /autoindex
        {
            allow_methods GET POST DELETE;
            autoindex on;
            #autoindex off;
        }
        
        location /redirect
        {
            return 301 /index.html;
        }
        
        location /google
        {
            return 302 https://www.google.com;
        }
    }
}