http {

    client_max_body_size 10M;

    # Servidor 1 - Puerto 8080
    server
    {
        listen 8080;
        index index.html;
        root html;
        error_page 400 /templates/error400.html;
        error_page 403 /templates/error403.html;
        error_page 404 /templates/error404.html;
        error_page 405 /templates/error405.html;
        error_page 413 /templates/error413.html;
        error_page 418 /templates/error418.html;
        error_page 500 /templates/error500.html;
        error_page 501 /templates/error501.html;
        
        location /autoindex
        {
            allow_methods GET POST DELETE;
            autoindex on;
        }
        
        location /redirect
        {
            return 301 /index.html;
        }
        
        location /google
        {
            return 302 https://www.google.com;
        }
    }

    # Servidor 2 - Puerto 8081
    server
    {
        listen 8081;
        index index.html;
        root html;
        error_page 400 /templates/error400.html;
        error_page 403 /templates/error403.html;
        error_page 404 /templates/error404.html;
        error_page 405 /templates/error405.html;
        error_page 413 /templates/error413.html;
        error_page 418 /templates/error418.html;
        error_page 500 /templates/error500.html;
        error_page 501 /templates/error501.html;
        
        location /autoindex
        {
            allow_methods GET POST DELETE;
            autoindex off;
        }
        
        location /redirect
        {
            return 301 /index.html;
        }
        
        location /google
        {
            return 302 https://www.google.com;
        }
    }

    # Servidor 3 - Puerto 8082
    server
    {
        listen 8082;
        index index.html;
        root html;
        error_page 400 /templates/error400.html;
        error_page 403 /templates/error403.html;
        error_page 404 /templates/error404.html;
        error_page 405 /templates/error405.html;
        error_page 413 /templates/error413.html;
        error_page 418 /templates/error418.html;
        error_page 500 /templates/error500.html;
        error_page 501 /templates/error501.html;
        
        location /autoindex
        {
            allow_methods POST DELETE;
            autoindex on;
        }
        
        location /redirect
        {
            return 301 /index.html;
        }
        
        location /google
        {
            return 302 https://www.google.com;
        }
    }
}
