http {

    client_max_body_size 10M;

    server
    {
        listen 8080;
        server_name localhost;
        root html;
        index index.html;
        error_page 400 /templates/error400.html;
        error_page 403 /templates/error403.html;
        error_page 404 /templates/error404.html;
        error_page 405 /templates/error405.html;
        error_page 500 /templates/error500.html;
        
        location /autoindex
        {
            allow_methods GET POST DELETE;
            autoindex on;
            #autoindex off;
        }
    }
}

